development:
  adapter: mysql
  database: rico
  host: localhost
  username: root
  password: 

test:
  adapter: mysql
  database: rico_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql
  database: rico_prod
  host: localhost
  username: root
  password: 
